#!/usr/bin/env bash
#
# Downloads the project-level JDK 27 Early Access build into ./.jdk/ and
# (re)generates .mvn/toolchains.xml so Maven uses it via the toolchains plugin.
#
# Binaries: https://jdk.java.net/27/  (build 24, 2026/05/29)
# Windows users: run setup-jdk.ps1 instead.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

BASE_URL="https://download.java.net/java/early_access/jdk27/24/GPL"

os="$(uname -s)"
arch="$(uname -m)"

case "$os" in
  Linux)  plat="linux" ;;
  Darwin) plat="macos" ;;
  *) echo "Unsupported OS: $os. Use setup-jdk.ps1 on Windows." >&2; exit 1 ;;
esac

case "$arch" in
  x86_64|amd64)  a="x64" ;;
  aarch64|arm64) a="aarch64" ;;
  *) echo "Unsupported architecture: $arch" >&2; exit 1 ;;
esac

file="openjdk-27-ea+24_${plat}-${a}_bin.tar.gz"
url="${BASE_URL}/${file}"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "Downloading ${url}"
curl -fSL -o "${tmp}/${file}" "$url"

echo "Verifying SHA-256 checksum"
curl -fSL -o "${tmp}/${file}.sha256" "${url}.sha256"
expected="$(awk '{print $1}' "${tmp}/${file}.sha256")"
if command -v sha256sum >/dev/null 2>&1; then
  actual="$(sha256sum "${tmp}/${file}" | awk '{print $1}')"
else
  actual="$(shasum -a 256 "${tmp}/${file}" | awk '{print $1}')"
fi
if [ "$expected" != "$actual" ]; then
  echo "Checksum mismatch!" >&2
  echo "  expected: $expected" >&2
  echo "  actual:   $actual" >&2
  exit 1
fi

echo "Extracting into .jdk/"
rm -rf .jdk
mkdir -p .jdk
tar xzf "${tmp}/${file}" -C .jdk

java_bin="$(find .jdk -type f -name java -path '*/bin/java' | head -1)"
if [ -z "$java_bin" ]; then
  echo "Could not locate java in extracted JDK." >&2
  exit 1
fi
jdk_home="$(cd "$(dirname "$java_bin")/.." && pwd)"
rel_home="${jdk_home#"$SCRIPT_DIR"/}"

echo "Writing .mvn/toolchains.xml (jdkHome=${rel_home})"
mkdir -p .mvn
cat > .mvn/toolchains.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<toolchains xmlns="http://maven.apache.org/TOOLCHAINS/1.1.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/TOOLCHAINS/1.1.0 http://maven.apache.org/xsd/toolchains-1.1.0.xsd">
  <!-- Generated by setup-jdk.sh. Project-level JDK 27 EA extracted into .jdk/ -->
  <toolchain>
    <type>jdk</type>
    <provides>
      <version>27</version>
      <vendor>openjdk</vendor>
    </provides>
    <configuration>
      <jdkHome>${rel_home}</jdkHome>
    </configuration>
  </toolchain>
</toolchains>
EOF

echo
echo "JDK 27 EA ready:"
"$jdk_home/bin/java" -version
echo
echo "Build with: ./mvnw clean verify"
