#Requires -Version 5.1
<#
.SYNOPSIS
    Downloads the project-level JDK 27 Early Access build into .\.jdk\ and
    (re)generates .mvn\toolchains.xml so Maven uses it via the toolchains plugin.

.DESCRIPTION
    Binaries: https://jdk.java.net/27/  (build 24, 2026/05/29)
    macOS / Linux users: run setup-jdk.sh instead.
#>
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

$baseUrl = 'https://download.java.net/java/early_access/jdk27/24/GPL'
$file    = 'openjdk-27-ea+24_windows-x64_bin.zip'
$url     = "$baseUrl/$file"

$tmp = Join-Path ([System.IO.Path]::GetTempPath()) ([System.Guid]::NewGuid().ToString())
New-Item -ItemType Directory -Force -Path $tmp | Out-Null
try {
    $zip = Join-Path $tmp $file

    Write-Host "Downloading $url"
    Invoke-WebRequest -Uri $url -OutFile $zip

    Write-Host 'Verifying SHA-256 checksum'
    $expected = ((Invoke-WebRequest -Uri "$url.sha256").Content.Trim() -split '\s+')[0]
    $actual   = (Get-FileHash -Algorithm SHA256 -Path $zip).Hash
    if ($expected.ToLower() -ne $actual.ToLower()) {
        throw "Checksum mismatch! expected=$expected actual=$actual"
    }

    Write-Host 'Extracting into .jdk\'
    $jdkDir = Join-Path $root '.jdk'
    if (Test-Path $jdkDir) { Remove-Item -Recurse -Force $jdkDir }
    New-Item -ItemType Directory -Force -Path $jdkDir | Out-Null
    Expand-Archive -Path $zip -DestinationPath $jdkDir -Force

    $javaExe = Get-ChildItem -Path $jdkDir -Recurse -Filter 'java.exe' |
        Where-Object { $_.Directory.Name -eq 'bin' } | Select-Object -First 1
    if (-not $javaExe) { throw 'Could not locate java.exe in extracted JDK.' }
    $jdkHome = Split-Path -Parent $javaExe.Directory.FullName
    $relHome = $jdkHome.Substring($root.Length).TrimStart('\', '/') -replace '\\', '/'

    Write-Host "Writing .mvn\toolchains.xml (jdkHome=$relHome)"
    $mvnDir = Join-Path $root '.mvn'
    New-Item -ItemType Directory -Force -Path $mvnDir | Out-Null
    $toolchains = @"
<?xml version="1.0" encoding="UTF-8"?>
<toolchains xmlns="http://maven.apache.org/TOOLCHAINS/1.1.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/TOOLCHAINS/1.1.0 http://maven.apache.org/xsd/toolchains-1.1.0.xsd">
  <!-- Generated by setup-jdk.ps1. Project-level JDK 27 EA extracted into .jdk/ -->
  <toolchain>
    <type>jdk</type>
    <provides>
      <version>27</version>
      <vendor>openjdk</vendor>
    </provides>
    <configuration>
      <jdkHome>$relHome</jdkHome>
    </configuration>
  </toolchain>
</toolchains>
"@
    Set-Content -Path (Join-Path $mvnDir 'toolchains.xml') -Value $toolchains -Encoding UTF8

    Write-Host ''
    Write-Host 'JDK 27 EA ready:'
    & "$jdkHome\bin\java.exe" -version
    Write-Host ''
    Write-Host 'Build with: .\mvnw.cmd clean verify'
}
finally {
    Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
}
